owner: dineshBvc
repo: ubiquitousGoggles

sites:
  - name: BVC
    url: https://www.bvc24.com
  - name: BVC24.IN
    url: https://www.bvc24.in
  - name: CMS
    url: https://cms.bvc24.in
  - name: UPT # For Fun
    url: https://uptime.bvc24.in

assignees:
  - dineshBvc
  - tamilmctv
  - jayanandhini-tech

status-website:
  cname: uptime.bvc24.in
  logoUrl: https://cms.bvc24.in/assets/icon/favicon.ico
  name: BVC
  introTitle: "**BVC services** - Status"
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
i18n:
  footer: This code for this site is [open source and MIT Licensed](https://raw.githubusercontent.com/dineshBvc/ubiquitousGoggles/refs/heads/master/LICENSE). The content of this site is [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/).
